name: 🔍 Notificación - Consulta de Cliente

on:
  issues:
    types: [opened]  # Se activa cuando alguien abre un Issue en GitHub

  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: 📢 Notificar al equipo sobre la consulta de un cliente
        run: echo "🔔 Un cliente ha sido consultado en el sistema."

      - name: ✅ Registrar evento en los logs
        run: echo "$(date) - Cliente consultado" >> logs.txt
